# Generated by Django 3.0.8 on 2020-07-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
    ]
