# Generated by Django 3.0.8 on 2020-07-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Unknown Title', max_length=50),
        ),
    ]
